# 工作流程的名稱
name: Deploy to Cloud Run

# 觸發條件：當有程式碼推送到 main 分支時
on:
  push:
    branches:
      - main

# 環境變數，方便在整個工作流程中重複使用
env:
  PROJECT_ID: modular-buffer-467407-i0 # 直接寫死專案 ID
  SERVICE_NAME: food-search-api # 您在 Cloud Run 上的服務名稱
  REGION: asia-east1 # 您 Cloud Run 服務的區域

jobs:
  deploy:
    # 指定此工作在最新的 Ubuntu 環境中運行
    runs-on: ubuntu-latest
    
    # 授予 GitHub Actions 寫入 Google Cloud 的權限
    permissions:
      contents: 'read'
      id-token: 'write'

    steps:
      # 步驟 1: 從 GitHub 倉庫中取得您的程式碼
      - name: Checkout
        uses: actions/checkout@v4

      # 步驟 2: 使用服務帳戶金鑰 (Service Account Key) 進行 GCP 驗證
      - name: Google Auth
        id: auth
        uses: 'google-github-actions/auth@v2'
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY }}

      # 步驟 3: 建置並部署到 Cloud Run
      # ★★★ 修正點：改回使用來源碼部署模式 ★★★
      # 'source: .'' 會將當前目錄的程式碼打包上傳至 Google Cloud Build，
      # 由 Cloud Build 自動完成建置和推送 Docker 映像檔的所有步驟。
      - name: Deploy to Cloud Run
        id: deploy
        uses: 'google-github-actions/deploy-cloudrun@v2'
        with:
          service: ${{ env.SERVICE_NAME }}
          region: ${{ env.REGION }}
          # 告訴 Cloud Run 從當前目錄的 Dockerfile 建置
          source: '.'
          # 將 GitHub Secrets 作為環境變數傳遞給 Cloud Run 服務
          env_vars: |
            AZURE_OPENAI_ENDPOINT=${{ secrets.AZURE_OPENAI_ENDPOINT }}
            AZURE_OPENAI_API_KEY=${{ secrets.AZURE_OPENAI_API_KEY }}
            AZURE_OPENAI_EMBEDDING_DEPLOYMENT=${{ secrets.AZURE_OPENAI_EMBEDDING_DEPLOYMENT }}
            AZURE_OPENAI_API_VERSION=${{ secrets.AZURE_OPENAI_API_VERSION }}
            QDRANT_URL=${{ secrets.QDRANT_URL }}
            QDRANT_API_KEY=${{ secrets.QDRANT_API_KEY }}
            DB_TYPE=${{ secrets.DB_TYPE }}
            DB_DRIVER=${{ secrets.DB_DRIVER }}
            DB_SERVER=${{ secrets.DB_SERVER }}
            DB_DATABASE=${{ secrets.DB_DATABASE }}
            DB_UID=${{ secrets.DB_UID }}
            DB_PWD=${{ secrets.DB_PWD }}
            DB_HOST=${{ secrets.DB_HOST }}
            DB_USER=${{ secrets.DB_USER }}
            DB_MYSQL_PASSWORD=${{ secrets.DB_MYSQL_PASSWORD }}
            DB_MYSQL_NAME=${{ secrets.DB_MYSQL_NAME }}

      # 步驟 4: 輸出部署後的服務網址
      - name: Show Output
        run: echo "Successfully deployed to ${{ steps.deploy.outputs.url }}"
